"use client";

const LiveTendersListData = [
  {
    refno: "	233839164",
    worklink: "/tender18",
    work: "Tender For gem portal Multifunction Machines MFM (Q2) ,",
    date: "11 Sep, 2023",
    agency: "Office Of Dg (mss)",
    valuelink: "/tender18",
    value: "Refer Documents",
    location: "	Odisha",
    viewlink: "/tender18",
    whatsapp: "/tender18",
    icon: "/images/whatsapp-icon.webp",
  },
  {
    refno: "233838562",
    worklink: "/tender18",
    work: "TENDER FOR GEM PORTAL DIGITAL INVERTER FROST FREE DOUBLE DOOR REFRIGERATOR (Q3) ,",
    date: "19 Sep, 2023",
    agency: "Indian Army",
    valuelink: "/tender18",
    value: "Refer Documents",
    location: "Jammu & Kashmir",
    viewlink: "/tender18",
    whatsapp: "/tender18",
    icon: "/images/whatsapp-icon.webp",
  },
  {
    refno: "233838562",
    worklink: "/tender18",
    work: "TENDER FOR GEM PORTAL DIGITAL INVERTER FROST FREE DOUBLE DOOR REFRIGERATOR (Q3) ,",
    date: "19 Sep, 2023",
    agency: "Indian Army",
    valuelink: "/tender18",
    value: "Refer Documents",
    location: "Jammu & Kashmir",
    viewlink: "/tender18",
    whatsapp: "/tender18",
    icon: "/images/whatsapp-icon.webp",
  },
  {
    refno: "	233838563",
    worklink: "/tender18",
    work: "TENDER FOR GEM PORTAL FIRE EXTINGUISHER BALL AFO BALLS 3 KG (Q3) ,",
    date: "19 Sep, 2023",
    agency: "Indian Army",
    valuelink: "/tender18",
    value: "Refer Documents",
    location: "Jammu & Kashmir",
    viewlink: "/tender18",
    whatsapp: "/tender18",
    icon: "/images/whatsapp-icon.webp",
  },
  {
    refno: "233837108",
    worklink: "/tender18",
    work: "TENDER FOR GEM PORTAL HEXAGON HEAD BOLTS SCREWS AND NUTS OF PRODUCT GRADE ‘C’ AS PER IS 1363 (Q4) ,",
    date: "19 Sep, 2023",
    agency: "South Eastern Coalfields Limited",
    valuelink: "/tender18",
    value: "Refer Documents",
    location: "Madhya Pradesh",
    viewlink: "/tender18",
    whatsapp: "/tender18",
    icon: "/images/whatsapp-icon.webp",
  },
  {
    refno: "233839721",
    worklink: "/tender18",
    work: "TENDER FOR GEM PORTAL SPEED VARIER GUIDE OIL SEAL SET TRANSFORMER REPAIR PANEL REPAIR LABOUR CHARGES , SPARES",
    date: "19 Sep, 2023",
    agency: "Indian Army",
    valuelink: "/tender18",
    value: "Refer Documents",
    location: "West Bengal",
    viewlink: "/tender18",
    whatsapp: "/tender18",
    icon: "/images/whatsapp-icon.webp",
  },
  {
    refno: "233839722",
    worklink: "/tender18",
    work: "TENDER FOR GEM PORTAL FUEL TANK REPAIR FUEL FILTER GUIDE OIL SEAL ENGINE MACHINE OVERHAUL LED LIGHT CABIN LIGHT SPEED VARIER CABIN MOUNTING LABOUR CHARGES , SPARES",
    date: "19 Sep, 2023",
    agency: "Indian Army",
    valuelink: "/tender18",
    value: "Refer Documents",
    location: "West Bengal",
    viewlink: "/tender18",
    whatsapp: "/tender18",
    icon: "/images/whatsapp-icon.webp",
  },
  {
    refno: "	233838231",
    worklink: "/tender18",
    work: "TENDER FOR GEM PORTAL AGRICULTURE LAND LEVELER (Q3) ,",
    date: "19 Sep, 2023",
    agency: "Co-operative Department",
    valuelink: "/tender18",
    value: "Refer Documents",
    location: "Bihar",
    viewlink: "/tender18",
    whatsapp: "/tender18",
    icon: "/images/whatsapp-icon.webp",
  },
  {
    refno: "	233839723",
    worklink: "/tender18",
    work: "	TENDER FOR GEM PORTAL V BELT GASKET SET O RING SET HIGH PRESSURE PIPE BLOWER BEARING FIP OVERHAUL ENGINE HEAD OVERHAUL ENGINE BLOCK REPAIR ENGINE OIL MOUNTING PAD SELF STARTER OVERHAUL LABOUR CHARGES , SPARES",
    date: "19 Sep, 2023",
    agency: "Indian Army",
    valuelink: "/tender18",
    value: "Refer Documents",
    location: "West Bengal",
    viewlink: "/tender18",
    whatsapp: "/tender18",
    icon: "/images/whatsapp-icon.webp",
  },
  {
    refno: "233837269",
    worklink: "/tender18",
    work: "TENDER FOR GEM PORTAL ENERGY AUDIT SERVICE - LUMPSUM BASED - DETAILED; AS PER RFD ATTACHED ,",
    date: "30 Sep, 2023",
    agency: "South Central Railway",
    valuelink: "/tender18",
    value: "Refer Documents",
    location: "	Andhra Pradesh",
    viewlink: "/tender18",
    whatsapp: "/tender18",
    icon: "/images/whatsapp-icon.webp",
  },
];

export default LiveTendersListData;
