"use client";
import Icon from "../src/images/whatsapp-icon.webp";

const AllTendersListData = [
  {
    refno: "233912015",
    worklink: "/tender18",
    work: "TENDER FOR EPROCURE TENDER ESTIMATE FOR GREYWATER MANAGEMENT AND RECHARGE FROM HOUSE OF RAJU SEKH TO PIRTALA AT TANTIBASKA ,",
    date: "22 Sep, 2023",
    agency: "Zilla Parishad",
    valuelink: "/tender18",
    value: "187933",
    location: "West Bengal",
    viewlink: "/tender18",
    whatsapp: "/tender18",
    id: "r233912015",
    icon: Icon,
  },
  {
    refno: "233944099",
    worklink: "/tender18",
    work: "TENDER FOR EPROCURE TENDER CONSTRUCTION OF CC ROAD FROM BARSHPADA BASKI RAMDAS TO SAMEN MURMU HOUSE AT GOLHAT CHAKLA SANSAD COD NO 69725514 ,",
    date: "25 Sep, 2023",
    agency: "Zilla Parishad",
    valuelink: "/tender18",
    value: "100833",
    location: "West Bengal",
    viewlink: "/tender18",
    whatsapp: "/tender18",
    icon: Icon,
  },
  {
    refno: "233968185",
    worklink: "/tender18",
    work: "TENDER FOR RAILWAY TENDER INNER SPRING FOR WAG-5 LOLOMOTIVE",
    date: "23 Oct, 2023",
    agency: "WEST CENTRAL RAILWAY",
    valuelink: "/tender18",
    value: "Refer Documents",
    location: "Madhya Pradesh",
    viewlink: "/tender18",
    whatsapp: "/tender18",
    icon: Icon,
  },
  {
    refno: "233968182",
    worklink: "/tender18",
    work: "	TENDER FOR RAILWAY TENDER KIT FOR DRIVER DIRECT BRAKE VALVE FD-1 KIT TO FTRTIL PT NO. 790004105 AND D&M PT NO. RK AB3-T1 CONSIST OF FOLLOWING 06 ITEMS 07 NOS:- VALVE STEM ASSY. TO FTRTIL PT NO. 019101000 AND D&M PT NO. AB21-W3 QTY.1 SEAL TO FTRTIL PT NO. 04701000A AND D&M PT NO. 009-4 QTY.1 DIAPHRAGM TO FTRTIL PT NO. 001705000 AND D&M PT NO. 004- 7 QTY.1 JOINT TO FTRTIL PT NO. 001712500 AND D&M PT NO. 0016-1 QTY.1 STRAINER TO FTRTIL PT NO. 004401500 AND D&M PT NO. AB3-21 QTY.1 O-RING TO FTRTIL PT NO. 038704000A AND D&M PT NO. 0015-291 QTY.2.",
    date: "30 Sep, 2023",
    agency: "WEST CENTRAL RAILWAY",
    valuelink: "/tender18",
    value: "Refer Documents",
    location: "Madhya Pradesh",
    viewlink: "/tender18",
    whatsapp: "/tender18",
    icon: Icon,
  },
  {
    refno: "233968183",
    worklink: "/tender18",
    work: "TENDER FOR RAILWAY TENDER 3/2 - WAY DIRECT ACTING NORMALLY CLOSED",
    date: "30 Sep, 2023",
    agency: "WEST CENTRAL RAILWAY",
    valuelink: "/tender18",
    value: "Refer Documents",
    location: "Madhya Pradesh",
    viewlink: "/tender18",
    whatsapp: "/tender18",
    icon: Icon,
  },
  {
    refno: "233968181",
    worklink: "/tender18",
    work: "	TENDER FOR RAILWAY TENDER GEAR CASE MACHINED (MS). FOR WAG-7/WAG 9 LOCOS AS PER DRG.NO. AS PER CLW DRG. NO. - 1209.01.013.014 ALT -7 OR LA",
    date: "19 Sep, 2023",
    agency: "WEST CENTRAL RAILWAY",
    valuelink: "/tender18",
    value: "Refer Documents",
    location: "Madhya Pradesh",
    viewlink: "/tender18",
    whatsapp: "/tender18",
    icon: Icon,
  },
  {
    refno: "233961335",
    worklink: "/tender18",
    work: "TENDER FOR EPROCURE TENDER RE-CONSTRUCTION OF ICDS CENTER AT UTTAR PATIKHALI ,UT RECONSTRUCTION OF ICDS CENTER AT UTTAR PATIKHALI. AP-63/23-24 ID - 67660035)",
    date: "27 Sep, 2023",
    agency: "Zilla Parishad",
    valuelink: "/tender18",
    value: "216510",
    location: "West Bengal",
    viewlink: "/tender18",
    whatsapp: "/tender18",
    icon: Icon,
  },
  {
    refno: "233965769",
    worklink: "/tender18",
    work: "TENDER FOR EPROCURE TENDER CONSTRUCTION OF TOILET BLOCK NEAR ST. STAND SATARA ,",
    date: "25 Sep, 2023",
    agency: "Directorate Of Municipal Administration",
    valuelink: "/tender18",
    value: "2087310",
    location: "Maharashtra",
    viewlink: "/tender18",
    whatsapp: "/tender18",
    icon: Icon,
  },
  {
    refno: "233968282",
    worklink: "/tender18",
    work: "TENDER FOR RAILWAY TENDER HYTREL UPPER WASHER MATERIAL FOR PRIMARY",
    date: "30 oct, 2023",
    agency: "SOUTH EAST CENTRAL RAILWAY",
    valuelink: "/tender18",
    value: "Refer Documents",
    location: "Maharashtra",
    viewlink: "/tender18",
    whatsapp: "/tender18",
    icon: Icon,
  },
  {
    refno: "233968402",
    worklink: "/tender18",
    work: "TENDER FOR RAILWAY TENDER SET OF PILLAR FOR LHB COACHES",
    date: "19 oct, 2023",
    agency: "RAIL COACH FACTORY",
    valuelink: "/tender18",
    value: "Refer Documents",
    location: "Punjab",
    viewlink: "/tender18",
    whatsapp: "/tender18",
    icon: Icon,
  },
];

export default AllTendersListData;
