"use client";

const CareersListingData = [
  {
    time: "FULL TIME",
    title: "Business Development Manager",
    desc: "The candidate should have experience in e-commerce industry",
    btn1: "Details",
    btn2: "Apply",
    target1: "#details1",
    id1: "details1",
    target2: "#apply1",
    id2: "apply1",
    modaltitle: "Business Development Manager",
    experience: "Experience: Min 5 years",
    openings: "Openings: 3",
    li1: "MBA Graduates",
    li2: "Min 5 years experience in e-commerce industry",
    li3: "Fluent in English",
    li4: "Able to lead team dynamically",
    li5: "Good educator to ensure implementation of norms of the Company",
    li6: "Coordinate with team and the Management for better productivity",
    li7: "Resolve channel conflicts",
    li8: "A good trainer & self learner",
    li9: "Should have a proven track record",
    package: "3.00 Lacs to 4.00 Lacs",
    location: "Ahmedabad",
    index: "1",
  },
  {
    time: "FULL TIME",
    title: "Business Development Executives",
    desc: "The candidate should have experience in e-commerce industry",
    btn1: "Details",
    btn2: "Apply",
    target1: "#details2",
    id1: "details2",
    target2: "#apply2",
    id2: "apply2",
    modaltitle: "Business Development Executives1",
    experience: "Experience: Min 2 years",
    openings: "Openings: 10",
    li1: "Min Graduates",
    li2: "Min 2 years experience in tele sales",
    li3: "Good in convincing and closure techniques",
    li4: "Able to achieve targets",
    package: "3.00 Lacs to 4.00 Lacs",
    location: "Ahmedabad",
    index: "2",
  },
  {
    time: "FULL TIME",
    title: "Business Development Executives",
    desc: "The candidate should have experience in e-commerce industry",
    btn1: "Details",
    btn2: "Apply",
    target1: "#details2",
    id1: "details2",
    target2: "#apply2",
    id2: "apply2",
    modaltitle: "Business Development Executives",
    experience: "Experience: Min 2 years",
    openings: "Openings: 10",
    li1: "Min Graduates",
    li2: "Min 2 years experience in tele sales",
    li3: "Good in convincing and closure techniques",
    li4: "Able to achieve targets",
    package: "3.00 Lacs to 4.00 Lacs",
    location: "Ahmedabad",
    index: "2",
  },
];

export default CareersListingData;
